[project]
name = "myvllm"
version = "0.1.0"
description = "A custom vLLM project"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "transformers",
    "torch",
    "xxhash",
]
